### ISSUE TITLE
MySQL Forcing "root" username for configuration. (PR Request)

### ISSUE THREAD

**Issue by xCykrix** [netherfoam/MaxBans-4.0#37]
Hello! I was poking my head into this version of MaxBans as the other has some issues that refuse to be permanently changed.

When I configured MaxBans for MySQL from your guide, it always returns the username as root even though the config has another. It tried to connect and found the server, however is declined at authentication.

ERROR
```
[12:24:25 INFO]: [MaxBansPlus] Enabling MaxBansPlus v1.7
[12:24:25 INFO]: [io.sentry.DefaultSentryClientFactory] Using an HTTPS connection to Sentry.
[12:24:25 INFO]: [org.flywaydb.core.internal.util.VersionPrinter] Flyway 4.0.3 by Boxfuse
[12:24:25 WARN]: Sat Mar 03 12:24:25 EST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[12:24:25 ERROR]: [MaxBansPlus] Unable to migrate database. Disabling MaxBans
org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost:23306/convexity) for user 'root': Access denied for user 'root'@'localhost' (using password: YES)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:412) ~[maxbans-plus-1.7.jar:?]
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:370) ~[maxbans-plus-1.7.jar:?]
        at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50) ~[maxbans-plus-1.7.jar:?]
        at org.flywaydb.core.Flyway.execute(Flyway.java:1326) ~[maxbans-plus-1.7.jar:?]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917) ~[maxbans-plus-1.7.jar:?]
        at org.maxgamer.maxbans.MaxBansPlus.migrate(MaxBansPlus.java:81) ~[maxbans-plus-1.7.jar:?]
        at org.maxgamer.maxbans.MaxBansPlus.onEnable(MaxBansPlus.java:108) [maxbans-plus-1.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1337]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1337]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1337]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1337]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1337]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1337]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1337]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1337]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1337]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1337]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:873) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1710) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2188) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2219) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2014) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.12.2.jar:git-Paper-1337]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_151]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_151]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_151]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_151]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386) ~[patched_1.12.2.jar:git-Paper-1337]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) ~[patched_1.12.2.jar:git-Paper-1337]
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:409) ~[?:?]
        ... 17 more
```

CONFIGURATION
```
# The database to store bans, mutes, and addresses in
database:
   driver: "com.mysql.jdbc.Driver"
   url: "jdbc:mysql://localhost:23306/convexity"
   user: "xCykrix"
   password: "myMysqlPasswordIsHere"

# Whether the server should be treated as offline. Deleting this line means the servers configuration will be used.
# This serves as an override. Offline servers use names to uniquely identify players, online servers use their UUID's.
offline: false

# Each time a player is warned, they receive a strike. This specifies what each of those strikes mean for the player
warnings:
   penalties:
     1: "tell {{name}} This is your first warning"
     2: "tell {{name}} This is your final warning"
     3: "ban {{name}} 1 hour Warning limit reached:\n{{reason|No reason given}}"
   strikes: 3
   duration: "3 days"

# List of chat commands which are not allowed to be used when a player is muted. Examples are /tell and /broadcast
chat-commands: []

# This sends any errors that occur to Sentry (See https://sentry.io). These errors are then analysed by me, the author,
# and fixed! It means I can deliver you a more stable plugin, and you don't have to report problems. Disabling or
# deleting this line means I won't receive error reports and can't help you automagically :(
error-tracking: true
```

**Comment by xCykrix** [comment]
I'm not entirely sure if it is a problem my end or not. However I found the config reads right when setting up the stuff and am kinda working from there. But you may figure it out before I do.

**Comment by xCykrix** [comment]
Alright!
So it appears that FlywayUtil.java  from line 12 till end of statement returns "root" as the username.

```
public class FlywayUtil {
    public static Flyway migrater(JdbcConfig jdbc) {
        Flyway flyway = new Flyway();

        flyway.setClassLoader(Flyway.class.getClassLoader());
        System.out.println("Sources: " + jdbc.getUrl() + " : " + jdbc.getUsername() + " : " + jdbc.getPassword());
        flyway.setDataSource(jdbc.getUrl(), jdbc.getUsername(), jdbc.getPassword());

        // Fallback to h2 if no driver is available
        String type = "h2";
        if(jdbc.getDriver().contains("mysql")) {
            // MySQL uses a different set of migrations
            type = "mysql";

            // This allows use of databases which have existing tables in their database
            flyway.setBaselineVersion(MigrationVersion.fromVersion("1.0"));
            flyway.setBaselineOnMigrate(true);

            // We disable validation on migration v1.1 because of a legacy bug
            flyway.setCallbacks(new Flyway_MySQL_V1_1__Fix_Callback());
        }

        flyway.setLocations("db/migration/" + type);

        return flyway;
    }
}
```
The System.out.println() has everything correct except the username. If I figure it out from here of where it goes wrong, i'll definately make the fix myself :)

**Comment by xCykrix** [comment]
Oh my, that was a funny facepalm. Your config.md is incorrect on the formatting of your configuration file! Bah.

**Comment by xCykrix** [comment]
https://github.com/netherfoam/MaxBans-4.0/pull/38

**Comment by netherfoam** [comment]
Merged this, sorry about that!

This was an old bug that I fixed in the default config.yml file, but evidently I missed it inside of `config.md`!

Thanks very much for this :smile:
